name: Flutter Android Integration Test
on:
  push:
    branches:
      - main # Adjust this to match the branch where you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2 # Use the appropriate Flutter action version
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Set up Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30 # Use the desired Android API level
          target: default # Or use "google_apis" for an emulator with Google Play services
          arch: x86 

      - name: Start emulator
        run: emulator -avd emulator-30 -no-audio -no-window

      - name: Wait for emulator to start
        run: android-wait-for-emulator

      - name: Run integration tests
        run: flutter drive --driver=test_driver/integration_test.dart --target=test/integration/create_form_model_test.dart
