name: main
on: [push, workflow_dispatch]

jobs:

  android:
    runs-on: macos-11
    strategy:
      matrix:
        api-level:
          - 29
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # instead of "channel: stable", you could be more precise by specifying the exact version of Flutter you're using:
          # flutter-version: '<FLUTTER_VERSION>'
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Run widget_test
        run: flutter test
